### ISSUE TITLE
Vendor the fonts

### ISSUE THREAD

**Issue by bgstack15** [DarkflameUniverse/NexusDashboard#102]
Would you please bundle the fonts in the Nexus dashboard, so the client information is not leaked to google? I see only two requests:

* https://fonts.googleapis.com/css?family=Nunito:700
* https://fonts.gstatic.com/s/nunito/v26/XRXI3I6Li01BKofiOc5wtlZ2di8HDFwmdTQ3jw.woff2

**Comment by aronwk-aaron** [comment]
no, it just adds bloat to the repo. if you are concerned about "leaking client information" to google, just block google entirely and it will fallback to using the default font in the web browser

**Comment by bgstack15** [comment]
For anyone interested in doing this manually with the docker image, here's what I did:

1. Add to docker-compose.yml darkflameweb: a volume
```
- ${HOME}/darkflameserver/web/css:/app/static/css
```
2. Pull down the css file once, evaluate the include statement, save the font file, and adjust site.css to do this:
````
/* @import url(https://fonts.googleapis.com/css?family=Nunito:700); */
@font-face {
  font-family: 'Nunito';
  font-style: normal;
  font-weight: 700;
  src: url(XRXI3I6Li01BKofiOc5wtlZ2di8HDFwmdTQ3ig.ttf) format('truetype');
}
