### ISSUE TITLE
Moderation Approval Site "View" Button wont work and trow an Internal Server Error Page

### ISSUE THREAD

**Issue by BloodyHellcat** [DarkflameUniverse/NexusDashboard#51]
I have the following Error:
`NexusDahsboard           | [2022-10-11 20:27:05 +0000] [41] [ERROR] Exception on /characters/view/2 [GET]`
`NexusDahsboard           | Traceback (most recent call last):`
`NexusDahsboard           |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app`
`NexusDahsboard           |     response = self.full_dispatch_request()`
`NexusDahsboard           |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request`
`NexusDahsboard           |     rv = self.handle_user_exception(e)`
`NexusDahsboard           |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request`
`NexusDahsboard           |     rv = self.dispatch_request()`
`NexusDahsboard           |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request`
`NexusDahsboard           |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)`
`NexusDahsboard           |   File "/usr/local/lib/python3.8/site-packages/flask_user/decorators.py", line 58, in decorator`
`NexusDahsboard           |     return view_function(*args, **kwargs)`
`NexusDahsboard           |   File "/app/characters.py", line 95, in view`
`NexusDahsboard           |     if "i" in inv.keys() and type(inv["i"]) == list:`
`NexusDahsboard           | AttributeError: 'str' object has no attribute 'keys'`

This happens when I want to press the "View" Button on the Moderation Approval site.
I get a Internal Server Error on the Webinterface at the same time.

Anyone know if this is a me problem right now or generaly a problem still?

**Comment by BloodyHellcat** [comment]
What do you mean by VE?
I've closed the game and even restarted the server and still it give's me the same error.

At the same time, when loading the /moderation/all page, I'll get the folowing error poped up.
`DataTables warning: table id=property_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

**Comment by aronwk-aaron** [comment]
I will need logs from the system log page to diagnose this properly
