### ISSUE TITLE
BBB builds not showing in property viewer after latest BBB PR merge on server

### ISSUE THREAD

**Issue by HailStorm32** [DarkflameUniverse/NexusDashboard#54]
After updating the server with the BBB fix PR https://github.com/DarkflameUniverse/DarkflameServer/pull/725 , BBB models no longer render in the property viewer. Instead an error is thrown in the logs

![image](https://i.imgur.com/XqaKhCC.png)

**Property preupdate**
![image](https://i.imgur.com/5PjUXIr.jpg)

**Property post update**
![image](https://i.imgur.com/stQzoFy.jpg)

Dashboard is running on the latest commit

**Comment by aronwk-aaron** [comment]
update your app
