### ISSUE TITLE
ND looks for cdclient.sqlite when CDServer.sqlite is actually needed

### ISSUE THREAD

**Issue by luxaritas** [DarkflameUniverse/NexusDashboard#55]
If you provide it a cdclient instead of a CDServer, certain aspects of ND will not work (eg, the send mail page IIRC). ND should prefer opening CDServer.sqlite instead of cdclient.sqlite if present so that luclient can be symlinked to the same client dir as the DLU server

**Comment by aronwk-aaron** [comment]
I'll see about making it able to use both for easier configuration and backwards compatability
