### ISSUE TITLE
ENH: update to python 3.11 and update packages

### ISSUE THREAD

**Issue by aronwk-aaron** [DarkflameUniverse/NexusDashboard#68]
it needs to be done

**Comment by Coolfeather2** [comment]
As a temporary workaround, using venv and bumping greenlet to 2.0.0 gets it running on python 3.11
```
python3 -m venv .venv
source .venv/bin/activate
# edit requirements.txt so greenlet==2.0.0
pip install -r requirements.txt
```

**Comment by Dopes88** [comment]
What can we do for backports.zoneinfo?

**Comment by aronwk-aaron** [comment]
run the docker version, it works and you dont have to change the version of python on the host
I will not be providing debugging for individuals trying to run on newer python versions.
if someone want to upgrade it and submit a PR before I get around to it, go for it

**Comment by Xiphoseer** [comment]
Filed #88
