### ISSUE TITLE
Database is super bloated due to storage of raw json blobs

### ISSUE THREAD

**Issue by EmosewaMC** [DarkflameUniverse/NexusDashboard#76]
yep
![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/39972741/eb40f983-4716-46b9-a545-64b4e99a7169)

**Comment by aronwk-aaron** [comment]
*sigh*

**Comment by Jettford** [comment]
_cries_

**Comment by aronwk-aaron** [comment]
gonna make a migration to compress them in-place and handle them that way

**Comment by aronwk-aaron** [comment]
fixed

**Comment by aronwk-aaron** [comment]
Before
![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/26027722/1c7c2d78-4082-437d-a1e9-91b76adb8199)


After
![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/26027722/b4281cee-ea3c-4b25-9996-d32085c8d30d)
