### ISSUE TITLE
Docker Web Issue

### ISSUE THREAD

**Issue by pjmoura577** [DarkflameUniverse/NexusDashboard#90]
Issue going on with the nexusdashboard on docker
![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/64061583/33a0b937-07a0-4ff9-a1e6-bbe4e4329ebc)
![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/64061583/abef4e1c-be5e-4605-bdc7-3c152366eb50)

**Comment by Xiphoseer** [comment]
Presumable caused by me removing libsass as a dependency in #88 and webfilter calling `import sass` without depending on it because it's a plugin system?

**Comment by pjmoura577** [comment]
> Presumably caused by me removing libsass as a dependency in #88 and webfilter calling `import sass` without depending on it because it's a plugin system?

![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/64061583/d5dbd4ac-55eb-425c-a232-ec20c31b3263)

I think so

**Comment by Xiphoseer** [comment]
Turns out my https://github.com/DarkflameUniverse/NexusDashboard/blob/d6b0a91e4d156762bf6c4e1191ceaf7af0ad7b9c/.gitignore#L7-L8
was stale, so it didn't try to compile the scss locally and didn't get the error outside the clean environment of a container.
