### ISSUE TITLE
cdclient.sqllite UTF8 issues

### ISSUE THREAD

**Issue by Mar0xy** [DarkflameUniverse/NexusDashboard#96]
I tried getting cdclient.sqllite to work with the dashboard but each time I convert it and try to use it I keep getting the same errors around it not being able to decode UTF-8

![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/8841466/6ed21d9a-1c5b-4af7-8f60-047d44b16322)

**Comment by Xiphoseer** [comment]
Which tool did you use? <https://fdb.lu-dev.net> should handle UTF-8 correctly.

**Comment by Mar0xy** [comment]
> Which tool did you use? https://fdb.lu-dev.net/ should handle UTF-8 correctly.

I used the LCDR util originally as noted in the README
```txt
Use fdb_to_sqlite.py in lcdr's utilities on res/cdclient.fdb in the unpacked client to convert the client database to cdclient.sqlite
```

then I also tried with the version that the server generates which also produced the same issue

I also now tried the site you provided but the same error still occurs

![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/8841466/429efbe6-ba9e-415f-99c0-802dbdf1c316)


Though interestingly enough with the sqlite generated through the site I now also get these additional messages which I will assume are normal

![image](https://github.com/DarkflameUniverse/NexusDashboard/assets/8841466/75583046-88a6-4665-948e-a754a0315b30)

**Comment by Xiphoseer** [comment]
Are you sure it's using the one you converted at all and not an auto-converted `CDServer.sqlite`?

What do your settings and paths look like? What happens when you replace that name to have a standard "e" with an Sqlite editor?

**Comment by Mar0xy** [comment]
> Are you sure it's using the one you converted at all and not an auto-converted CDServer.sqlite?

This actually led me to figure out what was going on it was using the auto-converted CDServer.sqlite from the actual server as that is the path defined in the `docker-compose.yml` file on the server repo

After I changed
```txt
CD_SQLITE_LOCATION=/app/cdclient/
```
to
```txt
CD_SQLITE_LOCATION=/app/luclient/res/
```

It started working
